### ISSUE TITLE
Support Consul Tags and make DC optional

### ISSUE THREAD

**Issue by pchojnacki** [BuoyantIO/linkerd#230]
Setup I'm using heavily depends on Consul for service discovery.
I've looked at linkerd as a tool that would greatly help with that setup. 
But right now it seems to me that Linkerd consul integration is lacking some important features to be 100% usable.

dc - should be optional - as by default consul agent resolves queries to local 
you should be able to query services by tags, 

I also have mixed feeling about linkerd using v1/catalog consul api for service discovery instead of '/health/service'

As I'm new to both scala and finagle (including dtabs) I might have missed something so excuse my ignorance.

**Comment by olix0r** [comment]
hi @pchojnacki, thanks for the feedback!  While I have operational experience with other service discovery backends like zookeeper and kubernetes, I have only used consul in our test environment.  So this sort of feedback is very helpful!

> dc - should be optional - as by default consul agent resolves queries to local 

We include _dc_ in the naming structure so that we can support multi-dc service routing.  For example, in the following dtab, we send 90% of traffic to dc1 and 10% of traffic to dc2:
```
/srv => 9 * /io.l5d.consul/dc1 & 1 * /io.l5d.consul/dc2;
/host => /srv;
/method => /$/io.buoyant.http.anyMethodPfx/host;
/http/1.1 =>  /method;
```
And so in order to accomplish this, we want dc names to be part of the name structure.  If they are truly optional, it's difficult for us to distinguish service names and dc names.

One option would be to require a consul configuration block for every dc, e.g.:
```
namers:
- kind: io.l5d.experimental.consul
  host: 127.0.0.1
  port: 2181
  prefix /io.l5d.consul.local
- kind: io.l5d.experimental.consul
  host: 127.0.0.1
  port: 2181
  dc: dc2
  prefix /io.l5d.consul.dc2
```

Alternatively, perhaps we could give special treatment to _local_ dc, so that dc does not need to be named explicitly in a Dtab like:
```
/srv => /io.l5d.consul/local;
/host => /srv;
/method => /$/io.buoyant.http.anyMethodPfx/host;
/http/1.1 =>  /method;
```

> you should be able to query services by tags,

This is one place where I feel that consul's model does not mesh well with Dtabs.  I'm interested for input here.

In linkerd, names reflect some hierarchical address -- not a _query_.  Let's say that a service, _birdsvc_, has the tags: _master_, _agent_, _green_, & _blue_.  Since tags are not key-value -- we don't have _role=[master|agent]_ and _color=[green|blue]_ -- it's not clear how to encode these names into a path.  There is no obvious hierarchy.  

In our view--coming from other service discovery systems--all instances of a _service_ should be able to accept traffic equally.  Instead of having a _birdsvc_ with a _master_ tag, we would opt to have a _birdsvc-master_ service.  Basically, a _service_ is a load balancing unit.

Would you mind elaborating on how you lay out your services with tags?  It would be helpful to have some concrete cases in mind so that we can figure out a solution for this.

> I also have mixed feeling about linkerd using v1/catalog consul api for service discovery instead of '/health/service'

That's fair.  linkerd should be able to operate well without service health checks, since its load balancer is able to maintain its own view of what is healthy via latency measurements and circuit breaking. I think it's reasonable, though, to honor consul health-checking as well.

> As I'm new to both scala and finagle (including dtabs) I might have missed something so excuse my ignorance.

No worries ;)  You shouldn't have to be familiar with Scala or Finagle to use linkerd.  And Dtabs take some getting used to...

Again, thanks for the feedback!

**Comment by pchojnacki** [comment]
Thanks for thorough reply.
>>you should be able to query services by tags,

>This is one place where I feel that consul's model does not mesh well with Dtabs. I'm interested for input here.

One of the reasons we initially get into consul was its builtin DNS interface. I'm mentioning that because maybe following that interface schema might be how we could implement tags.
The schema is `[<tag>.]<service-name>.service.[<dc>.]consul`

This is still somewhat limited but I think for now `[<tag>.]<service-name>` could work well, at least it would give users flexibility they already have when using consul.

> Would you mind elaborating on how you lay out your services with tags? It would be helpful to have some concrete cases in mind so that we can figure out a solution for this.

Recently we started using tags to distinguish environments e.g. dev.svc vs staging.svc
We also use consul DNS interface pretty extensively so we are somewhat limited by DNS in what we do. So e.g we also have tags like dev-master where otherwise we could use 2 tags and filter accordingly.

Some of the consul based tools I've seen in the wild also parse tags content.

>Alternatively, perhaps we could give special treatment to local dc, so that dc does not need to be named explicitly in a Dtab like:

I'm sure there will be at least one company out there that will decide to name its DC local.

I'm sure there will be at least one company out there that will decide to name its DC local :- )

>```namers:
- kind: io.l5d.experimental.consul
  host: 127.0.0.1
  port: 2181
  prefix /io.l5d.consul.local
- kind: io.l5d.experimental.consul
  host: 127.0.0.1
  port: 2181
  dc: dc2
  prefix /io.l5d.consul.dc2
```
I really like this approach. Also maybe adding `requiredTags: dev` could work too.

> load balancer is able to maintain its own view of what is healthy via latency measurements and circuit breaking

In consul you can trigger maintenance mode on node or service that should be able to mark each affected service as unhealthy with expectation being that traffic should stop being routed there.

Also I think current Linkerd consul impl doesn't do that but I think it would help with reaction time if Linkerd was also using blocking queries to watch for updates in consul services.

>Again, thanks for the feedback!

Thanks for building linkerd! With zipkin and consul support it certainly seems to be the missing piece I was looking for.

**Comment by endzyme** [comment]
+1 would love to see tag support here. 

Personal preference would be nice to be able to route inline with Dtabs to tags:

```
/consul => /#/io.l5d.consul/dc1
/http/1.1/* => /consul
/http/1.1/*/tag => /consul/tag
```

We would like to route in the following manor:
* We could register a webappname and point it to the current version:  
`/consul/webappname => /consul/tag/1.0/webapp;`
* We could then do canary with the same format:  
`/consul/webappname => 9 * /consul/tag/1.0/webapp & 1 * /consul/tag/2.0/webapp;`

Our current method is to register our services in consul as `webapp-version` and then namerd can handle which should be the active version.

**Comment by awwithro** [comment]
+1

**Comment by wmorgan** [comment]
Thanks all. We'll be taking a look into this shortly.
