### ISSUE TITLE
'header' http identifier

### ISSUE THREAD

**Issue by olix0r** [BuoyantIO/linkerd#373]
The 'basic' http identifier is fairly rich, which is good; but overkill for many configurations. Write a 'header' http identifier that works as follows:
- accepts a _dstPrefix_, default: `/`
- accepts a _header_, default: `l5d-dst-id`
- reads this header from requests:
  - if it's a valid path append it to dstPrefix
  - if it's not a valid path, add it to dstPrefix as a path component

This can easily be used to support the `Host` header (whereas the _basic_ identifier includes methods, etc).  Furthermore, this allows applications that can't easily override Host (for instance HTTP libraries that only take a URL and forcefully set _host_) to use another header.  This also will be helpful for proxy applications that want to explicitly set a downstream i.e. from a residual.

**Comment by clhodapp** [comment]
I want to express that I think this would be tremendously helpful in making the request routing design that I'm working on more clean.

**Comment by wmorgan** [comment]
@clhodapp: thanks for the feedback! Can you give us a few more details about the use case you want to support? We're actively working on some identifier stuff (like this ticket) right now.

**Comment by clhodapp** [comment]
Sure, but you're going to get a lot more details about what I'm doing, not just
a few.

I'm currently working on putting together the pieces for a kubernetes-native
microservice application for my employer. The application is to have two layers,
an "frontend" layer, which provides RESTful APIs over HTTP, and a "backend"
layer, which sits behind the frontend layer, providing RPCish APIs over pieces
of the data model over a multiplexed protocol (Mux for now, HTTP/2 when it's
ready). The intention is to use linkerd heavily for routing within this system:
These services will be run in the context of Kubernetes pods fronted by
Kubernetes Services. Each pod will contain a linkerd container, deployed in what
your docs call the "sidecar linker-to-linker" model. It's my intention to
configure these linkerd sidecars to connect to a namerd running the k8s
Endpoints Namer.

This works great for routing requests _within_ the cluster, which makes sense,
as I think this closely matches the use-case Bouyant has been focusing on, but I
think there's another very significant potential use case for "Finagle in a
box": HTTP ingress routing. First, I'll describe the vision of how I'd like this
deployment model to look. Then I'll describe what I'm actually planning to do to
come as close to this vision as possible using present day linkerd.

What I'd like to have happen is for Kubernetes Endpoints that declare an HTTP
port and are tagged with appropriate Kubernetes Labels to be automatically
"mounted" as versioned API groups on a virtual API host, which is actually
backed by the whole Kubernetes cluster (well a namespace therein). That is, if I
create a Kubernetes Service with an HTTP port and Kubernetes Labels,
`{"api-group": "users", "api-version": "v1", "exposed-api": "true"}`, I want
that API group to automatically become exposed at, e.g.,
`api.example.com/users/v1` on the public internet. I want a request for, e.g.,
`api.example.com/users/v1/profiles/123` to pass through my public routing and
balancing layer, where it will and have its path rewritten to `/profiles/123`
and for it to get routed to one of my service instances.

In order to come as close to this as is feasible with present-day linkerd, I've
gone ahead and set up a Kubernetes Deployment of NGINX-linkerd duo pods, which
are exposed to the public internet via a more-basic connection-level load
balancer. The NGINX part of these "public balancer" pods strips the first two
segments from the path and rewrites the `Host` header to a hyphenated
concatonation. For example, a `POST` to the path `/users/v1/profiles` is
rewritten to a `POST` to `/profiles` with a `Host` header of `users-v1`. The
request is then handed off to the linkerd running on `localhost` to be routed to
its final destination. That linkerd is configured to use the Endpoints Namer to
route the request based on a Kubernetes Endpoint with the name from the `HOST`
header. To ensure that only services which we fully intend to expose on the
public internet can recieve traffic via this mechanism, require that the port we
are routing to be named `public-http`.

The reason that this issue is of interest to me is that it will allow me to stop
overwriting the `Host` header and still route the request where it's supposed to
go. This means that the only non-additive mangling of the request that I'll have
to do in my routing layer is to strip the first two path segments.

Now some disconnected thoughts:

On my TODO list is to investigate what this Namer does when the Kubernetes
master (and thus the Kubernetes API) goes down. Specifically, I am wondering
whether the Endpoints Namer can continue to resolve names against cached data
while the Kubernetes master is down and whether it will correctly reconnect to
the API and resume consuming it when it comes back up. It would be great for the
intended k8s Endpoint Namer behavior to be described here and for the actual
behavior to go into the docs if possible, as it seems pretty important for users
of pretty much any Kubernetes API based infrastructure component to understand
what happens to that component when the API goes down.

It would be great if the Endpoints Namer could be more dynamic. Specifically, it
would be wonderful if it had support for Kubernetes Labels and Label-based
filtering. Suppose I could define a namer config like so:
```
  - kind: io.l5d.k8s
    experimental: true
    host: localhost
    port: 8001
    prefix: k8s
    namespaceFilters: [ ]
    endpointFilters:
      - kind: label
        name: exposed-api
        value: true
    portFilters:
      - kind: name
        value: http
    pathSegments:
      namespaceFilters:
        - kind: name
      endpointFilters:
        - kind: label
          name: api-group
        - kind: label
          name: api-version
        - portFilters: [ ]
```
This looks complex at first but it's also _super_ powerful and I don't think
it'd be all that hard to implement. What it says is to recognize paths that look
like:
```
/#/k8s/<namespace_name>/<endpoint_api-group_label_value>/<endpoint_api-version_value>
```
That is, the path `/#/k8s/ns/users/v1` would be balanced across all the pods in
all the services in the namespace `ns` with the Label values: `exposed-api=true,
api-group=profiles, api-version=v1`. I think in `NameTree`-land, the really
correct form of this is just a four-level `Union` (do note that single-child
Unions get optimized away): one to allow balancing across all criteria-matching
namespaces, another for balancing across matching Endpoints, another for
balancing across Pods within these Endpoints, and a final level for balancing
across exposed ports on those pods. It would be quite feasible for the Namer to
read Annotations on these objects to get weights for balancing as well. It
should also not be all that difficult to maintain the data structure to be able
to efficiently perform lookups, given that the potential query structure is
statically defined in the configuration. I actually have some ideas about the
particular way that this could be implemented if it's of any use, but I don't
think they are particularly novel, so I'll leave off on laying them out for now.

If this (admittedly-at-least-medium-sized) improvement plus the one mentioned in
this issue were made, linkerd would TRULY excel at routing with a Kubernetes
cluster, both as an RPC proxy and as an http ingress router (when coupled with
an NGINX helper).
