### ISSUE TITLE
Prefix bound names with # path segment

### ISSUE THREAD

**Issue by adleong** [BuoyantIO/linkerd#393]
In order to easily differentiate bound paths (ie paths that are to be processed by a namer rather than by delegation) we should apply the convention where bound paths start with a # path segment.

e.g. /#/io.l5d.fs/foobar

That is, /# should be prepended to the prefix of all namers.

This makes delegations easier to understand because it will be more immediately obvious which paths are "terminal".

**Comment by klingerf** [comment]
One thing I realized with this change is that it will be difficult for folks to know that they have to update their configs.  I had a namerd config with:

```
    namers:
    - kind: io.l5d.experimental.k8s
      host: localhost
      port: 8001
    storage:
      kind: io.buoyant.namerd.storage.inMemory
      namespaces:
        default: |
          /ns         => /io.l5d.k8s;
          /iface      => /ns/prod;
          /srv        => /iface/incoming;
          /host       => /srv;
          /http/1.1/* => /host;
```

After picking up this change, namerd still happily loaded that config, but routing was broken because the `/ns => /io.l5d.k8s` entry was no longer doing anything useful.  It's unfortunate that `/ns => /io.l5d.k8s` is _still_ a valid entry, even though its effect has changed entirely.  It makes me think we might want to do something drastic like abort linkerd/namerd startup if we recognize that baseDtab has an old namer string that's not prefixed with a "#".

**Comment by adleong** [comment]
Totally valid concern.  We'd have to hardcode a list of "old namer strings" and warn and/or abort if we see them.  We'd probably also only want to keep that check around for 1 or 2 versions: enough to give users a chance to transition but not keep it around forever.  

Ideally this type of error would be trivial to debug by looking at the delegator UI, but I suspect most of our users wouldn't know to do that.

**Comment by klingerf** [comment]
I encountered another subtle upgrade issue with this change and the tls bound path matcher.  I'm not sure there's anything we can do about it, but I wanted to post it here in case other folks run into similar.

Suppose I have a linkerd config as follows:

    namers:
    - kind: io.l5d.experimental.k8s
      host: localhost
      port: 8001
    routers:
    - protocol: http
      label: demo
      identifier:
        kind: io.l5d.path
      baseDtab: |
        /ns    => /io.l5d.k8s;
        /iface => /ns/kltest;
        /srv   => /iface/incoming;
        /http  => /srv;
      client:
        tls:
          kind: io.l5d.clientTls.boundPath
          caCertPath: /io.buoyant/linkerd/certs/cacertificate.pem
          names:
          - prefix: "/*/*/*/{service}"
            commonNamePattern: "{service}"
      servers:
      - port: 8080
        ip: 0.0.0.0

When I change the k8s namer dtab entry to `/ns => /#/io.l5d.k8s`, then I also have to change the tls boundPath prefix to `/*/*/*/*/{service}`, since the bound path for my service has changed from `/io.l5d.k8s/kltest/incoming/svcname` to `/#/io.l5d.k8s/kltest/incoming/svcname`.
