### ISSUE TITLE
Consider converting RouterService.apply's do{} to flatMap

### ISSUE THREAD

**Issue by stevej** [BuoyantIO/linkerd#446]
According to YourKit, about 8% of our allocations are occurring in 
`io.buoyant.router.RoutingFactory$RoutingService$$anonfun$apply$3$$anonfun$apply$4.apply(Object)`

within a flatMap. I think this is `RouterFactory.scala:98`, which is a transform of a `Req` to a `Future[Rsp]`. We should talk about rewriting this to something more procedural/less allocate-y. (if this does kill 8% of our allocations, it'd probably be worth a blog post, too)

**Comment by adleong** [comment]
Are you able to see what is being allocated in that method?  Looking at the code I see allocations of two closures (one passed to `rescue` and one passed to `ensure`) which probably show up a `PartialFunction` and `Function0`.  

Those closures can't just be `val`'d up though, because they capture some local variables.  

If scala isn't smart about how `for` is desugared, there might be allocations of `Function1` as well from the desugared `flatMap` calls.  Those should be easier to fix, if that's happening.

**Comment by olix0r** [comment]
My attempt to address this is here: https://github.com/buoyantio/linkerd/tree/ver/netty4-valed-routingfactory

I'll defer to @stevej to report on how much this helps

**Comment by stevej** [comment]
Our time to failure doubled but we're still full GC'ing after about 4 hours. I'll hook up YourKit and see if I can find this function in the hot path. Before, YourKit was claiming that this was like 8% of our allocations.

**Comment by stevej** [comment]
As I said in Slack, Alex and I didn't find evidence that it was directly helpful for reducing allocations. Considering closing this issue with a WELPWETRIED

**Comment by olix0r** [comment]
¯\_(ツ)_/¯
