### ISSUE TITLE
Rosetta Stone for LinkerD path and host-based routing

### ISSUE THREAD

**Issue by solidsnack** [BuoyantIO/linkerd#495]
We're looking for a Rosetta Stone translating between the Nginx conf we know and the LinkerD we don't. We'd like to do a setup like this:

```
http/1.1/*/web.example.com/* => web.internal.name
http/1.1/*/web.example.com/auth/* => auth.internal.name
http/1.1/*/fruits.example.com/* => fruits.internal.name
http/1.1/*/fruits.example.com/tomato/* => vegetables.internal.name
http/1.1/*/vegetables.example.com/* => vegetables.internal.name
```

For these examples, rewriting is not really useful. Would be great to example code and docs merged into LinkerD.

**Comment by wmorgan** [comment]
Ok, we discussed this a bit internally. I think there are basically two viable options:
1. Write a custom identifier that maps request URLs to names in the way that you want. (And potentially, we could come up with something more generic that you could then configure.)
2. Keep this logic in nginx, but have nginx set a Host header and pass through to linkerd, and have linkerd do routing based on the Host header.

Of these, I actually prefer the second, if you have any non-trivial nginx config, or want to do cookie parsing or arbitrary header parsing or whatever. But we can help you with the first one if you want.

(As a side note, it's technically possible to accomplish this sort of routing today with `httpUriInDst`, but it's almost definitely not what you want. It turns each distinct URI into a separate logic name and, since we cache and track stats per logical name, you're gonna have a Bad Time unless your URI space is severely constrained.)

**Comment by olix0r** [comment]
IIRC there was follow-up on this offline.  Please reopen if this is still an issue.
