### ISSUE TITLE
TTwitter protocol broken unexpectedly when linkerd enabled

### ISSUE THREAD

**Issue by mapix** [BuoyantIO/linkerd#602]
We run several TTwitter enabled Thrift RPC between Golang client and Python server on our production environment. Before Linkerd involved, it worked perfectly. When Linkerd first involved, it worked perfectly as before, the "100%" success rate made a very happy experience. But after several weeks, things got changed. Linkerd encountered a very high fail rate periodically, meanwhile client(Golang) TTwitter ResponseHeader frame got broken, it received some unknown type messages. The fail rate down to 0% once I restart Linkerd. And then it encountered again in hours.

                       Client( Golang)  ---> Linkerd(0.7.2) ---> Server (Python)

Thrift Version (Both Golang & Python) : 0.9.3

Zipkin client-side logic:

[zipkin/ttypes.go](https://github.com/mapix/shuai-go/blob/master/zipkin/ttypes.go#L1908)
``` 
1923 func (p *ResponseHeader) ReadField1(iprot thrift.TProtocol) error {
1924 ›   _, size, err := iprot.ReadListBegin()  // Here, Wrong message received
1925 ›   if err != nil {
1926 ›   ›   return thrift.PrependError("error reading list begin: ", err)
1927 ›   }
```

After long time troubleshoot, I find finagle will not send TTwitter ResponseHeader back when empty response received. But for a Scala beginner, i can't understand if it is the cause.
[TTwitterServerFilter.scala](https://github.com/twitter/finagle/blob/develop/finagle-thrift/src/main/scala/com/twitter/finagle/thrift/TTwitterServerFilter.scala#L75)
``` 
          Contexts.broadcast.let(env) {
            service(request_) map {
              case response if response.isEmpty => response // without ResponseHeader
              case response =>
                val responseHeader = new thrift.ResponseHeader
                ByteArrays.concat(
                  OutputBuffer.messageToArray(responseHeader, protocolFactory),
                  response)
            }
```

After restart second node linkerd,  it restored in calm.

![screen shot 2016-08-24 at 5 22 02 pm](https://cloud.githubusercontent.com/assets/932699/17925486/c02e9b04-6a1f-11e6-8b10-c598197afe44.png)

Linkerd config [here](http://pastebin.com/yVQELq5p).

[linkerd_dump.tar.gz](https://github.com/BuoyantIO/linkerd/files/434294/linkerd_dump.tar.gz)

**Comment by adleong** [comment]
Here is the commit that adds that header logic: https://github.com/twitter/finagle/commit/761b860b89188c24f70406db26003129dbadb6a1

Is the thrift method that you're calling a oneway method?  If so, the go client should not be attempting to read a response.  That said, I'm not sure why this would cause linkerd to have a degraded success rate until restart.

**Comment by mapix** [comment]
@adleong  thanks for your reply, but it is not a One-Way request , description file like this:

pickad.thrift
```
struct Query {
    1: i32 uid,
    2: string bid,
    3: i32 group_id,
    4: string ip,
    5: i32 hour,
    6: string pid,
    7: i32 unit_id,
    8: list<string> page_tags,
}

service PickAd {
    list<i32> get(1: Query query,
                  2: list<i32> ad_ids,
                  3: string model_typ,
                  4: string model_collection),
}
```

**Comment by adleong** [comment]
Ah, rats.  Would it be possible to capture a tcp dump, ideally of both the linkerd <-> python side and the golang <-> linkerd side?  Instructions for capturing a tcp dump are here: https://linkerd.io/help/
A metrics dump of linkerd would also be helpful.

**Comment by mapix** [comment]
@adleong  Yeah,  i will do both tcp dump and metrics dump, and will paste here in hours.  Thanks for your advise.

**Comment by mapix** [comment]
@adleong  
uploaded as [linkerd_dump.tar.gz](https://github.com/BuoyantIO/linkerd/files/434294/linkerd_dump.tar.gz)

```
.
|-- collect_metrics.sh
|-- collect_tcpdump.sh
|-- l5d_metrics_1472025753.json
|-- l5d_metrics_1472025813.json
|-- linkerd.2016-08-24-16:02.pcap
`-- README

0 directories, 6 files
```
tcpdump file include all traffic from client <-> linkerd & linkerd <-> server

**Comment by adleong** [comment]
Thanks for the metics and pcap, @mapix.  

Looking at the metrics I see a large number of channel closed exceptions:
`"rt//dae_thrift_client_proxy/dst/id/#/io.l5d.serversets/dae/services/thrift/glorfindel/PickAd/failures/com.twitter.finagle.ChannelClosedException/java.io.IOException":3479`
and an even larger number of connect exceptions:
`"rt//dae_thrift_client_proxy/dst/id/#/io.l5d.serversets/dae/services/thrift/glorfindel/PickAd/service_creation/failures/com.twitter.finagle.ChannelWriteException/java.net.ConnectException":26564043`

This indicates that linkerd is unable to connect to the python service for some reason.  Perhaps some kind of network issue?  Or could the python service have been rescheduled but its location not updated in ZooKeeper?

Looking at the pcap suggests this timeline of events:
* client sends a thrift request to linkerd
* linkerd fails to connect to server, throws `java.net.ConnectException: Connection refused: hador7/192.168.1.67:43920`
* linkerd returns an exception to client
* client attempts to parse the response as a list instead of as an exception, fails

I also notice that the ip address that linkerd is attempting to connect to (192.168.1.67) is not in the list of servers in the readme.  Perhaps that is further evidence that the serverset in ZooKeeper is stale?

For next debugging steps, when you see this issue again, I would recommend sending a request to linkerd and noting the response.  It will likely be an exception containing a `Connection refused` message.  You can then attempt to manually connect to the address in the exception and try to diagnose why linkerd can't connect to it.

**Comment by mapix** [comment]
@adleong   Thanks for the invaluable analysis.  

I simulated the zookeeper register logic in develop environment,  find a very long deregister which may lead the "Connection refused".  But still can't tell why TTwitter protocol broken,  the simulate shows that Linkerd always send back a ResponseHeader frame even connection refused occurs.

**Comment by mapix** [comment]
@adleong  

After reimplement our service register logic use standalone golang daemon, It works now.  Thank you very much for help.
