### ISSUE TITLE
Move responseClassifier from router block to client block

### ISSUE THREAD

**Issue by esbie** [BuoyantIO/linkerd#620]
We should consider moving it into the client block since that’s probably a more appropriate place.

Next time we have to make a breaking config format change, we could do this at the same time.

**Comment by olix0r** [comment]
Routers use response classifiers in several ways:
- Clients use response classifiers to determine success/failure counts.
- Routers use response classifiers to determine success/failure counts, and to determine whether a request is retryable.
- Servers use response classifiers to determine success/failure counts.

We measure response classifications at all three places because they each have different values.  Specifically:
* A client is connected to a single concrete cluster.
* A router sends requests to logical names.  Retries occur in the router (and not the client) so that retries may occur across clusters (i.e. when weighted destinations are used).
* Since a router may expose multiple servers, we track request counts (and success/failure) for each server.  Also, because retries happen in the router, server counts represent the original inbound request rate.

So, I think it's correct for classifiers to be configured on the router level so that requests are classified uniformly.

**Comment by esbie** [comment]
Thanks for the info!
