### ISSUE TITLE
Remove `baseDtab` in favor of `io.l5d.static` interpreter

### ISSUE THREAD

**Issue by olix0r** [BuoyantIO/linkerd#725]
Once #724 is complete, there is no good reason for baseDtab to be a top-level router configuration parameter.  For all but the default interpreter, the baseDtab is effectively useless.  Moving the baseDtab configuration into the interpreter section makes this much cleaner.  (Also, looking forward to an io.l5d.fs interpreter ;)

**Comment by adleong** [comment]
Your wish has already been granted: https://github.com/BuoyantIO/linkerd/pull/573

I'm starting to have doubts about baking the dtab into the default interpreter.  This would make it so that the dtab is no longer editable in the dtab playground.  It's also worth pointing out that dtabs are stacked on top of each and therefore the baseDtab isn't useless for other interpreters, it's submitted and appended.  For example, if a baseDtab is specified on a router that uses the namerd interpreter, that baseDtab will be sent as part of namerd requests and namerd will append it to it's own dtab for resolving that request.

**Comment by olix0r** [comment]
After discussion, I don't think that this particular change makes that much sense...
