### ISSUE TITLE
Allow retries for other status codes than 5xx

### ISSUE THREAD

**Issue by alinvasile** [BuoyantIO/linkerd#780]
Our apps are deployed in a cluster of independent tomcat web servers. Each app deployed there registers itself in a server set in zookeeper, but once the app is undeployed on one of them, linkerd keeps sending the requests to that web server. The server responds with 404, which is considered by linkerd as valid.

Is it possible to specify a list of status codes that must be retried? It is the case now for 5xx, but would be nice if we can specify 404 as well.

**Comment by adleong** [comment]
This could be accomplished by adding a ResponseClassifier to https://github.com/BuoyantIO/linkerd/blob/master/linkerd/protocol/http/src/main/scala/io/buoyant/linkerd/protocol/http/ResponseClassifiers.scala that classifies 404s as retryable failures.

What version of linkerd are you running?  If you are using a version older than 0.7.5 you can also try setting `enableProbation` to false so that hosts will be removed from the load balancers as soon as they are removed from service discovery (zookeeper).

**Comment by alinvasile** [comment]
I'm using 0.8.2.

I will try to update the code and submit a patch if possible.
